language: python

python:
  - 2.6
  - 2.7
  - 3.2

install:
  - pip install --use-mirrors tornado msgpack-python
  - python setup.py install

script:
  - python test/test_msgpackrpc.py --timeout-test
